pim_comment_comment_delete:
    path: /comment/{id}/remove
    defaults: { _controller: pim_enrich.controller.rest.product_comment:deleteAction }
    requirements:
        id: \d+
    methods: [DELETE]
